# Generated by Django 4.0.3 on 2022-03-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_email_cliente_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emails',
            new_name='email',
        ),
    ]
